SEED_LISTINGS = [
    {"property_type": "apartment", "location": "Yerevan, Kentron", "price": "$120000", "rooms_number": 2, "features": ["renovated", "balcony", "city view"]},
    {"property_type": "apartment", "location": "Yerevan, Arabkir", "price": "$98000", "rooms_number": 2, "features": ["new building", "parking", "elevator"]},
    {"property_type": "house", "location": "Yerevan, Avan", "price": "$185000", "rooms_number": 4, "features": ["garden", "garage", "quiet street"]},
    {"property_type": "apartment", "location": "Gyumri, Center", "price": "$65000", "rooms_number": 3, "features": ["sunny", "storage", "near park"]},
    {"property_type": "townhouse", "location": "Yerevan, Davtashen", "price": "$142000", "rooms_number": 3, "features": ["private yard", "family friendly", "modern kitchen"]},
    {"property_type": "apartment", "location": "Yerevan, Nor Nork", "price": "$73000", "rooms_number": 2, "features": ["affordable", "public transport", "open balcony"]},
    {"property_type": "house", "location": "Ashtarak", "price": "$110000", "rooms_number": 5, "features": ["large garden", "mountain view", "fireplace"]},
    {"property_type": "apartment", "location": "Yerevan, Malatia-Sebastia", "price": "$89000", "rooms_number": 3, "features": ["renovated", "school nearby", "central heating"]},
    {"property_type": "villa", "location": "Tsaghkadzor", "price": "$260000", "rooms_number": 6, "features": ["sauna", "panoramic view", "tourist area"]},
    {"property_type": "apartment", "location": "Yerevan, Shengavit", "price": "$81000", "rooms_number": 2, "features": ["metro nearby", "quiet courtyard", "furnished"]},
    {"property_type": "house", "location": "Vanadzor", "price": "$92000", "rooms_number": 4, "features": ["fruit trees", "garage", "renovated bathroom"]},
    {"property_type": "apartment", "location": "Yerevan, Ajapnyak", "price": "$77000", "rooms_number": 2, "features": ["elevator", "new windows", "near supermarket"]},
    {"property_type": "studio", "location": "Yerevan, Kentron", "price": "$69000", "rooms_number": 1, "features": ["compact", "central location", "short-term rental potential"]},
    {"property_type": "house", "location": "Dilijan", "price": "$150000", "rooms_number": 4, "features": ["forest nearby", "wood interior", "tourism potential"]},
    {"property_type": "apartment", "location": "Yerevan, Kanaker-Zeytun", "price": "$86000", "rooms_number": 3, "features": ["bright", "family area", "parking"]},
    {"property_type": "townhouse", "location": "Yerevan, Erebuni", "price": "$134000", "rooms_number": 3, "features": ["newly built", "small garden", "solar water heater"]},
    {"property_type": "house", "location": "Sevan", "price": "$128000", "rooms_number": 4, "features": ["lake proximity", "guest room", "barbecue area"]},
    {"property_type": "apartment", "location": "Yerevan, Arabkir", "price": "$115000", "rooms_number": 3, "features": ["high floor", "city view", "renovated"]},
    {"property_type": "villa", "location": "Jermuk", "price": "$210000", "rooms_number": 5, "features": ["spa area", "large terrace", "nature"]},
    {"property_type": "apartment", "location": "Yerevan, Kentron", "price": "$140000", "rooms_number": 3, "features": ["premium renovation", "downtown", "furnished"]},
]
